#!/usr/bin/env python
# coding: utf-8
"""Userdefined exceptions.

This module contains userdefined exceptions.
"""


class TypeError(Exception):
    """Exception raised during check of datatypes of function parameters."""


def __init__(self):
    my_message = 'Eine Ã¼bergebene Variable hat einen falschen Datentyp'
    self.my_message = my_message
